version: '3'

volumes:
  download:

services:
  make-vm:
    entrypoint:
      - /bin/sh
      - -c
      - "wget https://raw.githubusercontent.com/CristianHenzel/dockerfiles/master/alpine-make-vm-image/config.sh -O /usr/local/bin/config.sh && /usr/local/bin/config.sh start"
    image: hecristi/alpine-base:latest
    volumes:
      - download:/download
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - download:/var/www
