version: '3.1'
services:
  rsync-manager:
    image: hecristi/alpine-base
    environment:
      RSYNC_SERVER: 'true'
    volumes:
      - /data:/rsync/data
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  rsync-worker:
    image: hecristi/alpine-base
    environment:
      RSYNC_SERVER: 'rsync-manager'
      RSYNC_FOLDERS: 'example1,example2'
      RSYNC_STIME: 3
      RSYNC_FLAGS: '-aEzim --delete --timeout 10'
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
