#!/bin/bash

set -euxo pipefail

[ ! -f /tmp/ipstore ] && touch /tmp/ipstore

OLD_IP=$(cat /tmp/ipstore)
CURRENT_IP=$(curl -s "https://api.ipify.org")

while true; do
	if [ "${CURRENT_IP}" != "${OLD_IP}" ]; then
		echo "IP change detected from ${OLD_IP} to ${CURRENT_IP}"

		DO_RECORD_ID=$(curl -s -X GET -H "Content-Type: application/json" \
			-H "Authorization: Bearer ${DO_TOKEN}" \
			"https://api.digitalocean.com/v2/domains/${DO_DOMAIN}/records" | \
			jq '.domain_records[] | select(.type == "A" and .name == "${DO_SUBDOMAIN}") | .id')

		curl -s -X PUT -H "Content-Type: application/json" \
			-H "Authorization: Bearer ${DO_TOKEN}" \
			-d '{"data":"'"$CURRENT_IP"'"}' \
			"https://api.digitalocean.com/v2/domains/${DO_DOMAIN}/records/${DO_RECORD_ID}"

		echo -n "${CURRENT_IP}" > /tmp/ipstore
	fi

	sleep "${INTERVAL}"
done
