#!/bin/bash

set -euo pipefail

[ ! -f /tmp/ipstore ] && echo "0.0.0.0" > /tmp/ipstore

while true; do
	OLD_IP=$(cat /tmp/ipstore)
	CURRENT_IP=$(curl -s "https://api.ipify.org")

	if [ ${#CURRENT_IP} -le 15  ]; then
		if [ "${CURRENT_IP}" != "${OLD_IP}" ]; then
			echo "$(date -R) - IP change detected from ${OLD_IP} to ${CURRENT_IP}"

			DO_RECORD_ID=$(curl -s -X GET -H "Content-Type: application/json" \
				-H "Authorization: Bearer ${DO_TOKEN}" \
				"https://api.digitalocean.com/v2/domains/${DO_DOMAIN}/records" | \
				jq ".domain_records[] | select(.type == \"A\" and .name == \"${DO_SUBDOMAIN}\") | .id")

			DNS_REC=$(curl -s -X PUT -H "Content-Type: application/json" \
				-H "Authorization: Bearer ${DO_TOKEN}" \
				-d "{\"data\":\"$CURRENT_IP\"}" \
				"https://api.digitalocean.com/v2/domains/${DO_DOMAIN}/records/${DO_RECORD_ID}" | \
				jq -r ".domain_record.data")

			if [ "${DNS_REC}" != "${CURRENT_IP}" ]; then
				echo "$(date -R) - Error updating DNS. Current DNS: ${DNS_REC}"
			fi

			echo -n "${CURRENT_IP}" > /tmp/ipstore
		fi
	fi

	sleep "${INTERVAL}"
done
